import numpy as np
import matplotlib.pyplot as plt

x=np.loadtxt("datos1.dat", usecols=0)
y=np.loadtxt("datos1.dat", usecols=2)
z=np.loadtxt("datos1.dat", usecols=1)

x1=np.loadtxt("datos2.dat", usecols=0)
y1=np.loadtxt("datos2.dat", usecols=2)
z1=np.loadtxt("datos2.dat", usecols=1)

plt.figure(figsize=(30,20))
plt.subplot(2,3,1)
plt.plot(x,y)
plt.xlabel("x")
plt.ylabel("y")
plt.title("Método Euler")
plt.subplot(2,3,2)
plt.plot(x,z)
plt.xlabel("x")
plt.ylabel("dy/dx")
plt.title("Método Euler")
plt.subplot(2,3,3)
plt.plot(y,z)
plt.xlabel("y")
plt.ylabel("dy/dx")
plt.title("Método Euler")
plt.subplot(2,3,4)
plt.plot(x1,y1)
plt.xlabel("x")
plt.ylabel("y")
plt.title("Método Runge Kutta")
plt.subplot(2,3,5)
plt.plot(x1,z1)
plt.xlabel("x")
plt.ylabel("dy/dx")
plt.title("Método Runge Kutta")
plt.subplot(2,3,6)
plt.plot(y1,z1)
plt.xlabel("y")
plt.ylabel("dy/dx")
plt.title("Método Runge Kutta")

plt.savefig("SegundaDerivada.png")