import numpy as np
import matplotlib.pyplot as plt

x=np.loadtxt("euler.dat", usecols=0)
y=np.loadtxt("euler.dat", usecols=2)
z=np.loadtxt("euler.dat", usecols=1)

x1=np.loadtxt("rk4.dat", usecols=0)
y1=np.loadtxt("rk4.dat", usecols=2)
z1=np.loadtxt("rk4.dat", usecols=1)

x2=np.loadtxt("leapfrog.dat", usecols=0)
y2=np.loadtxt("leapfrog.dat", usecols=2)
z2=np.loadtxt("leapfrog.dat", usecols=1)

plt.figure(figsize=(10,10))
plt.subplot(3,3,1)
plt.plot(x,y)
plt.xlabel("Time")
plt.ylabel("Position")
plt.ylim(-1.5,1.5)
plt.xlim(0, 4*np.pi)
plt.title("Euler")
plt.subplot(3,3,2)
plt.plot(x1,y1)
plt.xlabel("Time")
plt.ylim(-1.5,1.5)
plt.xlim(0, 4*np.pi)
plt.title("RK")

plt.subplot(3,3,3)
plt.plot(x2,y2)
plt.xlabel("Time")
plt.ylim(-1.5,1.5)
plt.xlim(0, 4*np.pi)
plt.title("Leap frog")

plt.subplot(3,3,4)
plt.plot(x,z)
plt.xlabel("Time")
plt.ylabel("Velocity")
plt.ylim(-1.5,1.5)
plt.xlim(0, 4*np.pi)
plt.subplot(3,3,5)
plt.plot(x1,z1)
plt.xlabel("Time")
plt.ylim(-1.5,1.5)
plt.xlim(0, 4*np.pi)

plt.subplot(3,3,6)
plt.plot(x2,z2)
plt.xlabel("Time")
plt.ylim(-1.5,1.5)
plt.xlim(0, 4*np.pi)

plt.subplot(3,3,7)
plt.plot(y,z)
plt.xlabel("Position")
plt.ylabel("Velocity")
plt.ylim(-2,2)
plt.xlim(-2,2)
plt.subplot(3,3,8)
plt.plot(y1,z1)
plt.xlabel("Position")
plt.ylim(-2,2)
plt.xlim(-2,2)

plt.subplot(3,3,9)
plt.plot(y2,z2)
plt.xlabel("Position")
plt.ylim(-2,2)
plt.xlim(-2,2)

plt.savefig("SegundaDerivada.png")
